blank_issues_enabled: false
contact_links:
  - name: ❓ Support Question
    url: https://github.com/Cold-Development/Confirm2Drop/discussions
    about: Use GitHub discussions feature for questions
  - name: 👾 Discord server
    url: https://discord.colddev.dev
    about: Keep in touch in ColdDev's Discord server
